<a href="https://colab.research.google.com/github/kaitoyangja/dlab-d1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D1%EC%A3%BC_%EB%B0%B0%ED%8F%AC%ED%8C%8C%EC%9D%BCv1_2_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.코랩기본 사용법

## 1.1텍스트셀 사용해보기




##1.2 코드셀 사용하기

In [ ]:

print()

# 2.오류메시지 확인하기


In [ ]:
#참조변수없음
print(num)

NameError: name 'num' is not defined

In [ ]:
#SyntaxError  문법이 잘못된것
num = 1:
print(num)

In [ ]:
#TypeError : 타입이 안맞는것
a , b = "1" , "2"
c = a - b
print(c)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
#들여쓰기 IndentationError 에러
print(1)
 print(2)

In [ ]:
# ZeroDivisionError : 0으로 나눈것
a,b=1,0
c = a/b
print(c)


#3.리스트연습하기


In [ ]:
#list함수를 사용하여 1~20양의 정수리스트를 만들고 출력해 보세요.



In [ ]:
#리스트에서 짝수만 출력해보세요.



In [ ]:
#좋아하는 아이돌 리스트 만들기 5개 넣으세요.
li_idol = ['뉴진스','에스파','르세라핌','블랙핑크','아이브']
li_idol

In [ ]:
#마지막에 BTS추가하기

#3번째 '마마무'추가하기

#르세라핌의 인덱스를 찾아 '여자아이들'로 수정하기


#BTS 삭제하기


In [ ]:
#1~1000사이의 랜덤한 숫자 100개를 리스트에 넣어 항목수, 합계, 최소값, 최대값, 평균구하기

import random
li_num = []

for _ in range(100):
    li_num.append()

print("항목수 :",)
print("합계   :",)
print("최대값 :",)
print("최소값 :", )
print("평균   :",)

In [ ]:
#오름차순 정렬하기
li2 = li_num.copy()



In [ ]:
#내림차순정렬하기
li2 = li_num.copy()



#4.Numpy

In [ ]:
import numpy as np

In [ ]:
#list Data를 Numpy배열로 생성하기

list = [1,2,3,4,5]
print(list)



[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
#arr 인덱싱, 슬라이싱 가능
arr = np.array([1,2,3,4,5])
arr[2]

In [ ]:
arr[-3]

In [ ]:
arr = np.array([2,6,8,9,12,23,27,32,35])


In [ ]:
arr[::2]

In [ ]:
list = [1,2,3,4,5]
print(list)
arr = np.array(list)
print(arr)



[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#1부터 10까지 정수로 된 넘파이 배열 만들기
arr =
print(arr)

In [ ]:
#1에서 2까지 0.1간격의 소수로 이루어진 배열만들기
arr =
print(arr)

In [ ]:
#0에서 80까지 숫자중에서 6의 배수만 들어있는 배열만들기
arr =
arr

In [ ]:
#배열 arr에서 홀수번째 숫자들 2, 8, 12, 27, 35를 슬라이싱해보세요.
arr = np.array([2,6,8,9,12,23,27,32,35])


In [ ]:
#왜 list대신 numpy 사용효과를 알아봅시다.
arr = np.array(range(10000000))
arr

In [ ]:
# 시간 측적 함수 매크로 %%time과
%%time
list1 = []
for v in arr:
  if v % 2 == 0 and v % 8 == 0: #2의 배수이고 8의 배수인 숫자들
    list1.append(v)
print(len(list1))

In [ ]:
%%time
len( arr[(  ) & (  )]) #2의 배수이고 8의 배수인 숫자들

In [ ]:
#리스트의 모든값을 두배로 만들려면?
s = [2, 4, 6, 8, 10]
for i in range(len(s)):

print(s)

[4, 8, 12, 16, 20]


In [ ]:
#numpy로 모든값을 두배로 만들려면 ?
s = [2, 4, 6, 8, 10]
arr1 = np.array(s)

result = arr1 * 2
print(result)

In [ ]:
#list의 곱은?
s = [2, 4, 6, 8, 10]
print(s*2)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


In [ ]:
#arr의 사칙연산
s = [2, 4, 6, 8, 10]
arr1 = np.array(s)

print(result)


print(result)


print(result)


print(result)

In [ ]:
# 리스트간의 연산 결과는?
s = [2, 4, 6, 8, 10]
s2 = [5,10,15,20,25]

print(s+s2)

[2, 4, 6, 8, 10, 5, 10, 15, 20, 25]


In [ ]:
# 배열간의 연산결과는?
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([5,10,15,20,25])


print(result)


print(result)


print(result)


print(result)

[ 7 14 21 28 35]
[ -3  -6  -9 -12 -15]
[ 10  40  90 160 250]
[0.4 0.4 0.4 0.4 0.4]


#5.노션포트폴리오 페이지만들기